---
title: "google data analytics capstone project"
author: "Najith"
date: "1/23/2022"
output: html_document
---
#Fitness Tracer data Analysis
##Purpose of this analysis

To analyze smart device usage data in order to gain insight into how consumers use these products to track their activity.

This dataset used in this analysis is generated by respondents to a distributed survey via Amazon Mechanical Turk. Thirty three eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring.

#Loading Packages and data
importing all the needed libraries for data wrangling and data analysis.
```{r setup, include=FALSE}
install.packages("tidyverse")
install.packages("janitor")
install.packages("skimr")
install.packages("plotrix")

library(tidyverse)
library(janitor)
library(skimr)
library(lubridate)
library(tidyr)
library(ggplot2)
library(plotrix)
```

Reading the dataset (which are csv files) and converting the data into tibbles. 

```{r cars}
activity <- read_csv("dailyActivity_merged.csv")
calories <- read_csv("dailyCalories_merged.csv")
intensities <- read_csv("dailyIntensities_merged.csv")
steps <- read_csv("dailySteps_merged.csv")
sleep <- read_csv("sleepDay_merged.csv")
weight <- read_csv("weightLogInfo_merged.csv")
```

## Understanding the data

Lets start with exploring the data. We take a look at the data that we have.We are checking if there is any duplicates or null in the data.


```{r}
head(activity)
head(calories)
head(intensities)
head(steps)
head(sleep)
head(weight)

str(activity)
str(calories)
str(intensities)
str(steps)
str(sleep)
str(weight)

colnames(activity)
colnames(calories)
colnames(intensities)
colnames(steps)
colnames(sleep)
colnames(weight)

skim_without_charts(activity)
skim_without_charts(calories)
skim_without_charts(intensities)
skim_without_charts(steps)
skim_without_charts(sleep)
skim_without_charts(weight)

```
#Data Cleaning
We remove the duplicates in the dataset, so we use n_distinct to check distinct number of ids and we check for nulls and duplicate in the dataset.
```{r}
n_distinct(activity$Id)
n_distinct(calories$Id)
n_distinct(intensities$Id)
n_distinct(steps$Id)
n_distinct(sleep$Id)
n_distinct(weight$Id)

sum(duplicated(activity))
sum(is.na(activity))
sum(duplicated(calories))
sum(is.na(calories))
sum(duplicated(intensities))
sum(is.na(intensities))
sum(duplicated(steps))
sum(is.na(steps))
sum(duplicated(sleep))
sum(is.na(sleep))
sum(duplicated(weight))
sum(is.na(weight))
```
We see that there is duplicates in the sleep dataset so we should remove the duplicate
```{r}
sleep <- distinct(sleep)
sum(duplicated(sleep))
```
From dataset we see that the date and time in the dataset is of different format or sometime in the same column. Lets change the date in the dataset to the same format for all the tibbles and create a new column for time and have a uniform format. 
```{r}
activity_v2 <- activity %>% 
  mutate(ActivityDate = mdy(ActivityDate)) %>% 
  rename(date=ActivityDate)
steps_v2 <- steps %>% 
  mutate(ActivityDay = mdy(ActivityDay)) %>% 
  rename(date=ActivityDay)
intensities_v2 <- intensities %>% 
  mutate(ActivityDay = mdy(ActivityDay)) %>% 
  rename(date=ActivityDay)
calories_v2 <- calories %>%  
  mutate(ActivityDate = mdy(ActivityDay)) %>% 
  rename(date=ActivityDay)
sleep_v2 <- sleep %>% 
  mutate(SleepDay = mdy_hms(SleepDay),date = as.Date(SleepDay), 
  time = format(SleepDay, "%T"))
weight_v2 <- weight %>% 
  mutate(Date = mdy_hms(Date), date= as.Date(Date),
         time = format(Date, "%T"))

```
Delete the columns which contains the old date format and time. Check the number of rows after the duplicates are deleted.
```{r}
sleep_v3 <- sleep_v2
weight_v3 <- weight_v2

sleep_v3[,c("SleepDay")] <- list(NULL)
weight_v3[,c("Date")] <- list(NULL)

View(sleep_v3)
View(weight_v3)

nrow(sleep_v3)
nrow(weight_v3)
nrow(activity_v2)
```
Merging the activity and sleep dataset into a single dataset called activity_sleep for easy use.
```{r}
activity_sleep <- merge(activity_v2, sleep_v3, by= c("Id","date"), all=TRUE)
nrow(activity_sleep)
activity_sleep_wt <- merge(activity_sleep, weight_v3, by = c("Id", "date"), all=TRUE)
nrow(activity_sleep_wt)
View(activity_sleep_wt)
```
Add the weekdays column to the newly created dataset using mutate and creating a completely new dataset as activity_final.
```{r}
activity_final <- activity_sleep_wt %>%
  mutate(day = weekdays(date))
head(activity_final)
```
#Data Analysis
##Total steps vs Calories burnt
The hypothesis here is that the more steps is taken a day the more calories are burnt.
```{r}
ggplot(data=activity_final, aes(x=TotalSteps, 
                 y= Calories,
                 color=Calories)) +
  geom_point() +
  geom_smooth()
```
**Conclusion:**We see that the hypothesis is true and the Calories are burnt more the more total steps taken by the people is.
##Average steps VS Average sleep VS Average Calories burnt on weekdays
The more the people workout the more they should be tired so the more they should sleep. It might change depending on the data.Lets create a new dataset which has total steps and total minutes as sleep and average it up based on weekdays.
```{r}
avg_step_sleep <- activity_final %>% 
  select(day,TotalSteps, TotalMinutesAsleep) %>% 
  group_by(day) %>% 
  summarise(avg_step= mean(TotalSteps), avg_sleep= mean(TotalMinutesAsleep,na.rm = TRUE))

head(avg_step_sleep)
```
Lets check how the steps taken and the total minutes slept changes vary on each weekday.
```{r}
ggplot(data=avg_step_sleep)+
  geom_col(mapping= aes(x=day,y=avg_step,fill=avg_sleep),colour="black")+
  coord_flip()+
  scale_fill_gradient(low="white",high="red")
```
We see that they do not have a proportional relationship. But we also get to see that Thursday is the day where both the steps taken and the amount of sleep that people get are less on average.Lets We also check if the calories burnt and sleep has any relationship.

```{r}
avg_Calories_burnt_v1 <- activity_final %>% 
  select(day,Calories) %>% 
  group_by(day) %>% 
  summarise(avg_burnt_calories= mean(Calories))
head(avg_Calories_burnt_v1)

avg_Calories_burnt <- merge(avg_Calories_burnt_v1, avg_step_sleep, 
                            by= c("day"), all=TRUE)

ggplot(data=avg_Calories_burnt)+
  geom_col(mapping= aes(x=day,y=avg_burnt_calories,fill=avg_sleep),colour="black")+
  coord_flip()+
  scale_fill_gradient(low="white",high="red")
```
**Conclusion:**We see that on Thursdays on an average people sleep less as well as take lesser steps and so burn less calories than any weekdays.
##Device usage
Lets find the number of hours the devices is being used by people. We are splitting them into 3 types and they are as follows:
1. Light Use: Usage anywhere below 11 hours a day
2. Moderate Use: Usage anywhere above 11 hours and below or equal to 18 hours a day.
3. High Use: Usage above 18 hours and below or equal to 24 hours a day

This will give a breakdown of how much number of people use the devices each day.

```{r}
#Create total active minutes and total bed minutes of each person every day 
device_usage <- activity_final %>% 
  mutate(total_Activity_usage=(VeryActiveMinutes+FairlyActiveMinutes+
              LightlyActiveMinutes+SedentaryMinutes)/60, 
         total_sleep_usage=TotalTimeInBed/60) %>% 
  select(Id,date,day,total_Activity_usage,total_sleep_usage)
head(device_usage)

#type of usage people do each day

device_usage_type <- device_usage %>% 
  mutate(activity_type = case_when(
    total_Activity_usage<11 ~ "Light Use",
    total_Activity_usage>11 & total_Activity_usage<= 18 ~ "Modarate Use",
    total_Activity_usage<=24 ~ "High Use")) 

head(device_usage_type)
```
Lets visualise and see how the usage vary in the dataset, by using a bar chart visualization.
```{r}
ggplot(data=device_usage_type)+
  geom_bar(mapping=aes(x=day))+
  facet_wrap(~activity_type)+
  theme(axis.text.x = element_text(angle = 45))
```
People seem to use the device more between high use and moderate use each day. Now lets find the percentage of each type or the dataset.Lets visualize the percentage in a pie chart.
```{r}
usage_perc <- device_usage_type %>% 
  group_by(activity_type) %>% 
  summarise(total=n()) %>%
  mutate(count=sum(total)) %>% 
  group_by(activity_type) %>% 
  summarise(activity_type_perc= (total/count)*100) 

head(usage_perc)

pie3D(usage_perc$activity_type_perc,,labels= c("High","light", "Moderate"),
    border="Black", col= c("red", "yellow", "green"), radius = 1, explode=0.1,
    main="Device Usage")
```
**Conclusion:**We see that the people in the dataset use the devices on weekdays on an average more than 18 hours or more than 11 hours, which is high use and moderate use. 
## Average Minutes VS Intensities
The last analysis is to calculate the intensity level based on the amount of minutes spent during the morning run or walk.

Intensity level - Intensity level is the measure of energy exerted during the exercise or workout done by an individual.

In this analysis the intensity level is measured using four states

1.Very active
2.Fairly active
3.Lightly active
4.Sedentarily active

```{r}
activity_intensities  <- intensities_v2 %>% 
  group_by(Id) %>% 
  summarise(Very_Active_Minutes = mean(VeryActiveMinutes), 
            Fairly_Active_Minutes = mean(FairlyActiveMinutes),
            Light_Active_Minutes = mean(LightlyActiveMinutes),
            Sedentary_Active_Minutes = mean(SedentaryMinutes))
head(activity_intensities)

intensities_row <- c("Very_Active_Minutes", "Fairly_Active_Minutes",
                     "Light_Active_Minutes", "Sedentary_Active_Minutes")
avg_activity_intensities <- activity_intensities %>% 
  summarise(Mean_Very_Active_Minutes = mean(Very_Active_Minutes),
            Mean_Fairly_Active_Minutes=mean(Fairly_Active_Minutes),
            Mean_Light_Active_Minutes=mean(Light_Active_Minutes),
            Mean_Sedentary_Active_Minutes=mean(Sedentary_Active_Minutes))
head(avg_activity_intensities)

```
We now try to visualize the table using ggplot function.
```{r}
avg_intensities_pie <- avg_activity_intensities %>% 
  pivot_longer(everything()) %>% 
  rename(Minutes=name)
head(avg_intensities_pie)

ggplot(data = avg_intensities_pie) +
  geom_col(mapping= aes(x = Minutes, y = value, fill=Minutes),color="black") +
  labs(title = "Minutes Spent vs Intensity Level") +
  theme_void()
```
**Conclusion**: On an average, people spend more time (up to 80%) seated or relaxing, during or after their morning run or stroll.
#Inference
1.Calories are burnt more the more total steps taken by the people is. But there is no data for calories intake.
2.On Thursdays on an average people sleep less as well as take lesser steps and so burn less calories than any weekdays.
3.People in the dataset use the devices on weekdays on an average more than 18 hours or more than 11 hours, which is high use and moderate use. Its split between the two more or less into equal halves.
4.On an average, people spend more time (up to 80%) seated or relaxing, during or after their morning run or stroll.
#Recommendations
1.Create a feature in the device which also understands calories intake.
2.Offer some special achievements of promotions on thursdays to make people active and get enough sleep.
3.Working on an AI voice assistant that could be an added benefit that could motivate consumers to complete their daily goals to improve device usage and may also help avoid sedentary minutes.